# ============================ Filebeat Inputs =============================

filebeat.inputs:
  - type: filestream
    id: stos-logs
    enabled: true
    paths:
      - /home/stos/*.log

# =========================== General Settings ===========================

output.elasticsearch:
  hosts: ["http://172.20.3.115:9200"]
  username: "${ELASTIC_USERNAME:elastic}"
  password: "${ELASTIC_PASSWORD}"

# ======================= Optional Logging Configuration =======================
logging.level: debug  # Set to debug for more detailed output
logging.to_files: true
logging.files:
  path: /home/stos
  name: filebeat.log
  keepfiles: 7
  permissions: 0644
